apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: airflow-worker
  namespace: airflow
spec:
  scaleTargetRef:
    kind: StatefulSet
    name: airflow-worker
  minReplicaCount: 1
  maxReplicaCount: 5
  pollingInterval: 5
  cooldownPeriod: 60
  triggers:
    - type: redis
      metadata:
        address: airflow-redis.airflow.svc.cluster.local:6379
        listName: default          # ← TO JEST KLUCZ
        listLength: "10"            # testowo nisko, żeby nie przegapić backlogu
      authenticationRef:
        name: redis-auth
